services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    image: nestjs-backend:latest
    ports:
      - "4001:4001"
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    # Optionally add these:
    # env_file:
    #   - .env
    # depends_on:
    #   - postgres
